Prefix: "§8» §cAntiWerbung §8| §7"
no_perms: "Dafür hast du keine Rechte!"
help_message: "§c/antiwerbung < add | remove | list >"
no_args_add: "§c/antiwerbung add <domain>"
no_args_remove: "§c/antiwerbung remove <domain>"
no_domains_found: "§7Keine Domains vorhanden!"
domains_message: "§7Alle Domains: §e"
domains_separator: "§7, §e"
domain_successfully_added: "Die Domain §e{%0} §7wurde erfolgreich hinzugefügt!"
domain_successfully_removed: "Die Domain §e{%0} §7wurde erfolgreich entfernt!"
domain_already_exists: "Die angegebende Domain existiert bereits!"
domain_not_found: "Die angegebende Domain existiert nicht!"
player_use_domain_notify_msg1: "Ein Spieler wollte Werbung machen!"
player_use_domain_notify_msg2: "Spieler: §e{%0}"
player_use_domain_notify_msg3: "Message: §e{%0}"
player_dont_use_domain_message: "Bitte mache keine Werbung!"